# SPDX-License-Identifier: GPL-2.0-or-later
execute_process(COMMAND "${CMAKE_CXX_COMPILER}" -print-file-name=libvideoprt.a
  OUTPUT_VARIABLE video_library OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
get_filename_component(video_directory "${video_library}" DIRECTORY)
get_filename_component(mingw_root "${video_directory}" DIRECTORY)
set(ddk "${mingw_root}/include/ddk")
if(NOT EXISTS "${ddk}/video.h")
  message(FATAL_ERROR "Pinned MinGW DDK headers missing: ${ddk}")
endif()
function(dreamgpu_nt_driver target entry)
  set(driver_destination "drivers/nt5")
  if(ARGC GREATER 2)
    set(driver_destination "${ARGV2}")
  endif()
  dreamgpu_freestanding(${target})
  target_compile_options(${target} PRIVATE -Os -fno-ident -Wno-unused-parameter
    -Wno-multichar -Wno-cast-function-type)
  target_compile_definitions(${target} PRIVATE _WIN32_WINNT=0x0500 WINVER=0x0500 __USE_MINGW_ANSI_STDIO=0)
  target_include_directories(${target} PRIVATE "${ddk}")
  target_link_options(${target} PRIVATE -nostdlib -Wl,--subsystem,native,--no-insert-timestamp
    -Wl,--image-base,0x10000000,--major-os-version,5,--minor-os-version,0
    -Wl,--major-subsystem-version,5,--minor-subsystem-version,0 "-Wl,--entry,${entry}")
  set_target_properties(${target} PROPERTIES PREFIX "" RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/${driver_destination}")
  install(TARGETS ${target} RUNTIME DESTINATION "${driver_destination}" COMPONENT nt5)
endfunction()
add_library(dgpumini SHARED "${DREAMGPU_GUEST}/nt/miniport/bochsmp.cpp"
  "${DREAMGPU_GUEST}/nt/miniport/transport.cpp" "${DREAMGPU_GUEST}/nt/memory.cpp")
dreamgpu_nt_driver(dgpumini "_DriverEntry@8")
set_target_properties(dgpumini PROPERTIES SUFFIX ".sys")
target_link_libraries(dgpumini PRIVATE videoprt ntoskrnl hal gcc)
set(display_units enable palette pointer screen surface blit escape window)
set(display_sources "${DREAMGPU_GUEST}/nt/memory.cpp" "${DREAMGPU_GUEST}/nt/display.def")
foreach(unit IN LISTS display_units)
  list(APPEND display_sources "${DREAMGPU_GUEST}/nt/display/${unit}.cpp")
endforeach()
# The single production display driver implements normal system ICD discovery.
add_library(dgpudisp SHARED ${display_sources} "${DREAMGPU_GUEST}/nt/display/icd.cpp")
dreamgpu_nt_driver(dgpudisp "_DrvEnableDriver@12")
target_link_libraries(dgpudisp PRIVATE win32k gcc)

add_executable(dginst "${DREAMGPU_ROOT}/tools/nt/install.cpp")
dreamgpu_freestanding(dginst)
target_compile_options(dginst PRIVATE -Os)
target_compile_definitions(dginst PRIVATE _WIN32_WINNT=0x0500 WINVER=0x0500)
target_link_options(dginst PRIVATE -nostdlib -Wl,--entry,_WinMainCRTStartup@0
  -Wl,--subsystem,windows:5.0,--no-insert-timestamp)
target_link_libraries(dginst PRIVATE kernel32 user32 setupapi gcc)
set_target_properties(dginst PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/drivers/nt5")
install(TARGETS dginst RUNTIME DESTINATION drivers/nt5 COMPONENT nt5)
install(FILES "${DREAMGPU_GUEST}/nt/dreamgpu.inf" DESTINATION drivers/nt5 COMPONENT nt5)
install(FILES "${DREAMGPU_GUEST}/nt/COPYING" DESTINATION licenses/nt5 RENAME COPYING.txt COMPONENT nt5)
list(APPEND DREAMGPU_RUNTIME_TARGETS dgpumini dgpudisp dginst)
