# SPDX-License-Identifier: GPL-2.0-or-later
set(DREAMGPU_RUNNER_ID "" CACHE STRING "Rust-generated identity of runner source and build recipe")
string(LENGTH "${DREAMGPU_RUNNER_ID}" runner_id_length)
if(NOT runner_id_length EQUAL 64 OR NOT DREAMGPU_RUNNER_ID MATCHES "^[0-9a-f]+$")
  message(FATAL_ERROR "Rust orchestration must supply a 64-hex DREAMGPU_RUNNER_ID")
endif()
function(dreamgpu_tool target filename source)
  cmake_parse_arguments(TOOL "MEMORY;NT" "" "LIBRARIES;DEFINITIONS" ${ARGN})
  set(units "${DREAMGPU_ROOT}/tools/${source}")
  if(TOOL_MEMORY)
    list(APPEND units "${DREAMGPU_GUEST}/nt/memory.cpp")
  endif()
  add_executable(${target} ${units})
  dreamgpu_freestanding(${target})
  target_compile_options(${target} PRIVATE -O2 -Werror)
  if(TOOL_NT)
    target_compile_options(${target} PRIVATE -Wno-unused-parameter -Wno-multichar -Wno-cast-function-type)
    target_compile_definitions(${target} PRIVATE __USE_MINGW_ANSI_STDIO=0)
    set(version 0x0500)
    set(subsystem 5.0)
    set(directory nt5)
  else()
    set(version 0x0400)
    set(subsystem 4.0)
    set(directory common)
  endif()
  target_compile_definitions(${target} PRIVATE _WIN32_WINNT=${version} WINVER=${version} ${TOOL_DEFINITIONS})
  target_link_options(${target} PRIVATE -nostdlib "-Wl,--entry,_WinMainCRTStartup@0,--subsystem,windows:${subsystem},--no-insert-timestamp,--fatal-warnings")
  target_link_libraries(${target} PRIVATE kernel32 user32 ${TOOL_LIBRARIES} gcc)
  set_target_properties(${target} PROPERTIES OUTPUT_NAME "${filename}" SUFFIX ".EXE"
    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/tools/${directory}" LINKER_LANGUAGE C)
  install(TARGETS ${target} RUNTIME DESTINATION tools/${directory} COMPONENT tools)
  set(DREAMGPU_TOOL_TARGETS ${DREAMGPU_TOOL_TARGETS} ${target} PARENT_SCOPE)
endfunction()
dreamgpu_tool(dg_runner DGPUBEN benchmark/runner.cpp LIBRARIES advapi32 DEFINITIONS "DG_RUNNER_ID=\"${DREAMGPU_RUNNER_ID}\"")
target_compile_options(dg_runner PRIVATE -Os)
dreamgpu_tool(dg_setup DGSETUP benchmark/install.cpp MEMORY)
dreamgpu_tool(dg_hldebug DGHLDBG benchmark/hl-debug.cpp MEMORY)
dreamgpu_tool(dg_hlfocus DGFOCUS benchmark/hl-focus.cpp MEMORY)
dreamgpu_tool(dg_hlfocus_continue DGFOCUSR benchmark/hl-focus.cpp MEMORY DEFINITIONS DG_FOCUS_CONTINUE)
dreamgpu_tool(dg_hlfocus_return DGFRET benchmark/hl-focus.cpp MEMORY DEFINITIONS DG_FOCUS_CONTINUE DG_FOCUS_RETURN)
dreamgpu_tool(dg_input_observer DGKEYOBS benchmark/input-observer.cpp MEMORY)
dreamgpu_tool(dg_hlevidence DGHLEVID benchmark/renderer-log.cpp)
dreamgpu_tool(dg_nt_shutdown DGSTOP nt/shutdown.cpp LIBRARIES advapi32)
dreamgpu_tool(dg_wgl DGWGL opengl/probe.c MEMORY LIBRARIES gdi32)
dreamgpu_tool(dg_display_timing DGRATE display/timing-probe.cpp MEMORY LIBRARIES gdi32)
dreamgpu_tool(dg_system_gl DGSYSGL opengl/system-probe.cpp MEMORY LIBRARIES gdi32)
dreamgpu_tool(dg_border_gl DGBORDER opengl/system-probe.cpp MEMORY DEFINITIONS DG_GL_BORDER_PROBE LIBRARIES gdi32)
dreamgpu_tool(dg_capability_gl DGCAPGL opengl/capability.cpp MEMORY LIBRARIES gdi32)
dreamgpu_tool(dg_nt_rename DGRP nt/rename-probe.cpp NT MEMORY LIBRARIES advapi32)
dreamgpu_tool(dg_nt_restore DGRS nt/rename-probe.cpp NT MEMORY LIBRARIES advapi32 DEFINITIONS DG_RESTORE_RUNTIME)
dreamgpu_tool(dg_nt_runtime DGRT nt/runtime-probe.cpp NT MEMORY LIBRARIES advapi32)
dreamgpu_tool(dg_system_ddraw DGDD2D d3d/system2d-probe.cpp MEMORY LIBRARIES gdi32)
foreach(pair "window;DGWIN" "mode;DGMODE" "lifecycle;DGLOOP" "dual;DGDUAL")
  list(GET pair 0 source)
  list(GET pair 1 name)
  dreamgpu_tool(dg_${source} ${name} opengl/${source}-probe.c MEMORY LIBRARIES gdi32)
endforeach()
foreach(version 6 7 8 9)
  if(version LESS 8)
    set(source "d3d/probe${version}.cpp")
  else()
    set(source "d3d/probe.cpp")
  endif()
  dreamgpu_tool(dg_d3d${version} DGD3D${version} ${source} MEMORY LIBRARIES gdi32 DEFINITIONS DG_D3D_VERSION=${version})
  dreamgpu_tool(dg_system_d3d${version} DGSYS${version} ${source} MEMORY LIBRARIES gdi32 DEFINITIONS DG_D3D_VERSION=${version} DG_SYSTEM_D3D)
endforeach()
dreamgpu_tool(dg_capability_d3d6 DGCAP6 d3d/probe6.cpp MEMORY LIBRARIES gdi32
  DEFINITIONS DG_D3D_VERSION=6 DG_SYSTEM_D3D DG_CAPABILITY_D3D)
foreach(version 8 9)
  dreamgpu_tool(dg_capability_d3d${version} DGCAP${version} d3d/capability.cpp MEMORY
    DEFINITIONS DG_D3D_VERSION=${version})
endforeach()
foreach(pair "setup;DGUTSET" "probe;DGUT" "setup-d3d;DGUTDS" "logs;DGUTLOG")
  list(GET pair 0 source)
  list(GET pair 1 name)
  dreamgpu_tool(dg_ut_${source} ${name} unreal/${source}.cpp MEMORY)
  target_compile_options(dg_ut_${source} PRIVATE -Os -fanalyzer -Wno-unused-function)
endforeach()
dreamgpu_tool(dg_ut_d3d DGUTD3 unreal/probe.cpp MEMORY DEFINITIONS DG_UT_D3D)
target_compile_options(dg_ut_d3d PRIVATE -Os -fanalyzer -Wno-unused-function)
# The helpers need Win98's foreground API declarations, while imports remain
# dynamically bounded to APIs available on the accepted legacy OSes.
foreach(target dg_ut_setup dg_ut_probe dg_ut_setup-d3d dg_ut_logs dg_ut_d3d)
  get_target_property(definitions ${target} COMPILE_DEFINITIONS)
  list(REMOVE_ITEM definitions WINVER=0x0400)
  set_property(TARGET ${target} PROPERTY COMPILE_DEFINITIONS ${definitions} WINVER=0x0410)
endforeach()
if(DREAMGPU_BUILD_TRANSLATORS)
  dreamgpu_tool(dg_glide DGGLIDE glide/probe.cpp MEMORY DEFINITIONS __MSC__ WIN32)
  dreamgpu_tool(dg_system_glide DGSYSGR glide/probe.cpp MEMORY DEFINITIONS __MSC__ WIN32 DG_SYSTEM_GLIDE)
  foreach(target dg_glide dg_system_glide)
    target_include_directories(${target} PRIVATE "${DREAMGPU_GLIDE_SOURCE}")
  endforeach()
endif()
if(DREAMGPU_GUEST_OS STREQUAL "nt5")
  add_library(dg_loader_marker SHARED "${DREAMGPU_ROOT}/tools/nt/loader-marker.cpp")
  dreamgpu_freestanding(dg_loader_marker)
  target_compile_options(dg_loader_marker PRIVATE -O2 -Werror)
  target_compile_definitions(dg_loader_marker PRIVATE _WIN32_WINNT=0x0500 WINVER=0x0500)
  target_link_options(dg_loader_marker PRIVATE -nostdlib "-Wl,--entry,_DllMain@12,--subsystem,windows:5.0,--kill-at,--no-insert-timestamp,--fatal-warnings")
  target_link_libraries(dg_loader_marker PRIVATE kernel32 gcc)
  set_target_properties(dg_loader_marker PROPERTIES PREFIX "" OUTPUT_NAME DGPTST
    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/tools/nt5" LINKER_LANGUAGE C)
  install(TARGETS dg_loader_marker RUNTIME DESTINATION tools/nt5 COMPONENT tools)
  list(APPEND DREAMGPU_TOOL_TARGETS dg_loader_marker)
  add_library(dg_loader_original SHARED "${DREAMGPU_ROOT}/tools/nt/loader-marker.cpp")
  dreamgpu_freestanding(dg_loader_original)
  target_compile_options(dg_loader_original PRIVATE -O2 -Werror)
  target_compile_definitions(dg_loader_original PRIVATE _WIN32_WINNT=0x0500 WINVER=0x0500 DG_LOADER_ORIGINAL)
  target_link_options(dg_loader_original PRIVATE -nostdlib "-Wl,--entry,_DllMain@12,--subsystem,windows:5.0,--kill-at,--no-insert-timestamp,--fatal-warnings")
  target_link_libraries(dg_loader_original PRIVATE kernel32 gcc)
  set_target_properties(dg_loader_original PROPERTIES PREFIX "" OUTPUT_NAME DGNATIVE
    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/tools/nt5" LINKER_LANGUAGE C)
  install(TARGETS dg_loader_original RUNTIME DESTINATION tools/nt5 COMPONENT tools)
  list(APPEND DREAMGPU_TOOL_TARGETS dg_loader_original)
  dreamgpu_tool(dg_loader_child DGIMPLC nt/loader-child.cpp NT LIBRARIES dg_loader_marker)
  dreamgpu_tool(dg_loader_probe DGLOAD nt/loader-probe.cpp NT MEMORY LIBRARIES advapi32)
  dreamgpu_tool(dg_nt_install DGDRV nt/install.cpp NT DEFINITIONS DG_UNATTENDED LIBRARIES setupapi)
  dreamgpu_tool(dg_nt_diag DGDIAG nt/diagnose.cpp NT MEMORY LIBRARIES gdi32 setupapi cfgmgr32 advapi32)
  dreamgpu_tool(dg_nt_audit DGAUDIT nt/diagnose.cpp NT MEMORY DEFINITIONS DG_UNATTENDED LIBRARIES gdi32 setupapi cfgmgr32 advapi32)
  foreach(pair "gl;DGGL" "window;DGWIN" "cursor;DGCURSOR" "channel;DGCHAN")
    list(GET pair 0 source)
    list(GET pair 1 name)
    dreamgpu_tool(dg_nt_${source} ${name} nt/${source}-probe.cpp NT MEMORY LIBRARIES gdi32)
  endforeach()
else()
  dreamgpu_tool(dg_9_install DG9INST win9x/driver32.cpp MEMORY LIBRARIES advapi32 cfgmgr32 setupapi)
  dreamgpu_tool(dg_9_audit DG9AUDIT win9x/driver32.cpp MEMORY DEFINITIONS DG_DIAGNOSTIC LIBRARIES advapi32 cfgmgr32 setupapi)
endif()
# Source-only fixed bootstrap; separate from the driver and runner packages.
if(DREAMGPU_GUEST_OS STREQUAL "nt5")
  dreamgpu_tool(dg_serial_setup DGSERIAL benchmark/serial-setup.cpp NT LIBRARIES advapi32)
endif()
if(DREAMGPU_GUEST_OS STREQUAL "win98")
  dreamgpu_tool(dg_win98_icd_bootstrap DGICDBT opengl/win98-icd-bootstrap.cpp MEMORY LIBRARIES gdi32 advapi32)
  dreamgpu_tool(dg_win98_icd_inspect DGICDDI opengl/win98-icd-bootstrap.cpp MEMORY DEFINITIONS DG_ICD_INSPECT LIBRARIES gdi32 advapi32)
  dreamgpu_tool(dg_dma_request DGDMA win9x/dma32.c LIBRARIES cfgmgr32 setupapi advapi32 DEFINITIONS DG_DMA_READONLY=0)
  dreamgpu_tool(dg_dma_readonly DGDMAQ win9x/dma32.c LIBRARIES cfgmgr32 setupapi advapi32 DEFINITIONS DG_DMA_READONLY=1)
  dreamgpu_tool(dg_probe_update DGUPDATE win9x/probe-update32.c LIBRARIES advapi32)
  # Existing WinMain-only helpers use a tiny declared startup adapter; generated
  # here without modifying their source or requiring an interpreter.
  foreach(pair "loader32;DGLOAD" "setup32;DGSET9")
    list(GET pair 0 source)
    list(GET pair 1 name)
    set(wrapper "${CMAKE_BINARY_DIR}/${source}-startup.c")
    file(GENERATE OUTPUT "${wrapper}" CONTENT "#include \"${DREAMGPU_ROOT}/tools/win9x/${source}.c\"\nvoid WINAPI WinMainCRTStartup(void){ExitProcess(WinMain(GetModuleHandleA(0),0,0,0));}\n")
    add_executable(dg_${source} "${wrapper}")
    dreamgpu_user(dg_${source})
    target_link_options(dg_${source} PRIVATE -Wl,--entry,_WinMainCRTStartup@0)
    target_link_libraries(dg_${source} PRIVATE kernel32 user32 advapi32 gcc)
    set_target_properties(dg_${source} PROPERTIES OUTPUT_NAME "${name}" SUFFIX ".EXE" RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/tools/win98")
    list(APPEND DREAMGPU_TOOL_TARGETS dg_${source})
    install(TARGETS dg_${source} RUNTIME DESTINATION tools/win98 COMPONENT tools)
  endforeach()
  foreach(pair "channel32;DGCHAN9" "wgl32;DGWGL9" "mode32;DG9MODE" "cd32;DGCD" "identity32;DGID" "access32;DGACC")
    list(GET pair 0 source)
    list(GET pair 1 name)
    if(source STREQUAL "channel32")
      set(extension cpp)
    else()
      set(extension c)
    endif()
    add_executable(dg_${source} WIN32 "${DREAMGPU_ROOT}/tools/win9x/${source}.${extension}")
    dreamgpu_cpp(dg_${source})
    target_compile_options(dg_${source} PRIVATE -O2 -march=pentium3 -mno-sse -mno-sse2)
    if(NOT source MATCHES "^(channel32|wgl32)$")
      target_compile_options(dg_${source} PRIVATE -Wall -Wextra -Werror)
    endif()
    target_compile_definitions(dg_${source} PRIVATE _WIN32_WINNT=0x0400 WINVER=0x0400)
    target_include_directories(dg_${source} PRIVATE "${DREAMGPU_GUEST}/include" "${DREAMGPU_GUEST}/nt/include")
    target_link_options(dg_${source} PRIVATE -static-libgcc -Wl,--major-os-version,4,--minor-os-version,0,--major-subsystem-version,4,--minor-subsystem-version,0)
    target_link_libraries(dg_${source} PRIVATE kernel32 user32 gdi32 advapi32 winmm)
    set_target_properties(dg_${source} PROPERTIES OUTPUT_NAME "${name}" SUFFIX ".EXE" RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/tools/win98")
    list(APPEND DREAMGPU_TOOL_TARGETS dg_${source})
    install(TARGETS dg_${source} RUNTIME DESTINATION tools/win98 COMPONENT tools)
  endforeach()
  # Actual segmented NE diagnostics still require Open Watcom. These commands
  # preserve the real ABI rather than passing a fake Win16 model to clang.
  set(watcom_tools)
  foreach(pair "diagnose16;DG9DIAG;16" "blit16;DG9BLT;16")
    list(GET pair 0 source)
    list(GET pair 1 name)
    list(GET pair 2 bits)
    set(destination "${CMAKE_BINARY_DIR}/tools/win98/${name}.EXE")
    if(bits EQUAL 16)
      set(compiler wcl)
      set(options -bt=windows -l=windows -ms)
      set(headers win)
    else()
      set(compiler wcl386)
      set(options -bt=nt -l=nt_win)
      set(headers nt)
    endif()
    add_custom_command(OUTPUT "${destination}"
      COMMAND "${CMAKE_COMMAND}" -E make_directory "${CMAKE_BINARY_DIR}/tools/win98"
      COMMAND "${CMAKE_COMMAND}" -E env "WATCOM=${DREAMGPU_WATCOM_ROOT}"
        "PATH=${DREAMGPU_WATCOM_ROOT}/binl64:$ENV{PATH}" "INCLUDE=${DREAMGPU_WATCOM_ROOT}/h:${DREAMGPU_WATCOM_ROOT}/h/${headers}"
        "${DREAMGPU_WATCOM_ROOT}/binl64/${compiler}" -q ${options} -s -3
        "-i=${DREAMGPU_GUEST}/nt/include" "-i=${DREAMGPU_GUEST}/include" "-fe=${destination}"
        "${DREAMGPU_ROOT}/tools/win9x/${source}.c"
      WORKING_DIRECTORY "${DREAMGPU_VMDISP_SOURCE}" DEPENDS "${DREAMGPU_ROOT}/tools/win9x/${source}.c" VERBATIM)
    list(APPEND watcom_tools "${destination}")
    install(FILES "${destination}" DESTINATION tools/win98 COMPONENT tools)
  endforeach()
  add_custom_target(dreamgpu-win98-tools DEPENDS ${watcom_tools})
  list(APPEND DREAMGPU_TOOL_TARGETS dreamgpu-win98-tools)
endif()
