// SPDX-License-Identifier: GPL-2.0-or-later
//! One OS-selecting PE4 bootstrap, embedding already audited OS packages.
use crate::{capture, digest, run, write_json};
use anyhow::{Context, Result};
use serde_json::json;
use std::{collections::BTreeSet, fs, path::Path, process::Command};

fn safe_name(name: &str) -> bool {
    name.len() <= 180
        && !name.is_empty()
        && name.split('/').all(|part| {
            !part.is_empty()
                && !part.starts_with('.')
                && !part.ends_with('.')
                && part
                    .bytes()
                    .all(|c| c.is_ascii_alphanumeric() || b"._-".contains(&c))
                && ![
                    "CON", "PRN", "AUX", "NUL", "COM1", "COM2", "COM3", "COM4", "COM5", "COM6",
                    "COM7", "COM8", "COM9", "LPT1", "LPT2", "LPT3", "LPT4", "LPT5", "LPT6", "LPT7",
                    "LPT8", "LPT9",
                ]
                .contains(
                    &part
                        .split('.')
                        .next()
                        .unwrap()
                        .to_ascii_uppercase()
                        .as_str(),
                )
        })
}
fn rc_path(path: &Path) -> Result<String> {
    let path = path
        .canonicalize()?
        .to_str()
        .context("non-UTF8 resource path")?
        .to_owned();
    anyhow::ensure!(
        !path.contains(['"', '\n', '\r', '\\']),
        "unsafe resource path"
    );
    Ok(path)
}
fn audit_device_id_import(dump: &str) -> Result<()> {
    let mut module = String::new();
    let mut found = 0;
    for line in dump.lines() {
        if let Some(name) = line.trim().strip_prefix("DLL Name:") {
            module = name.trim().to_ascii_lowercase();
        } else if line
            .split_whitespace()
            .any(|word| word == "CM_Get_Device_IDA")
        {
            anyhow::ensure!(
                module == "cfgmgr32.dll",
                "CM_Get_Device_IDA must import from CfgMgr32: Windows 98 SetupAPI lacks it"
            );
            found += 1;
        }
    }
    anyhow::ensure!(found == 1, "missing or ambiguous device-ID import");
    Ok(())
}
fn prepare(output: &Path) -> Result<Vec<serde_json::Value>> {
    let input = output.join("build/setup-input");
    fs::create_dir_all(&input)?;
    let mut header = String::from("// Generated by dreamgpu-build; embedded package identities.\n#pragma once\nstruct Payload {unsigned os,id,size; const char *path,*sha;};\nstatic const Payload payloads[] = {\n");
    let mut resources = String::from("// Generated immutable package resources.\n");
    let mut evidence = Vec::new();
    let mut total_bytes = 0u64;
    let mut id = 100u32;
    for (os, name) in [(1, "win98"), (2, "windows2000-xp")] {
        let package = output.join("packages").join(name);
        let manifest: serde_json::Value =
            serde_json::from_slice(&fs::read(package.join("manifest.json"))?)?;
        anyhow::ensure!(manifest["guest_os"] == name, "wrong package family");
        let mut files = manifest["files"]
            .as_object()
            .context("package file map missing")?
            .clone();
        anyhow::ensure!(!files.is_empty(), "empty package");
        for extra in ["manifest.json", "package.json", "runner_manifest.json"] {
            files.insert(extra.into(), json!(digest(&package.join(extra))?));
        }
        let mut seen = BTreeSet::new();
        for (name, expected) in files {
            anyhow::ensure!(
                safe_name(&name) && seen.insert(name.to_ascii_lowercase()),
                "unsafe/colliding payload {name}"
            );
            let mut path = package.clone();
            for part in name.split('/') {
                path.push(part);
                anyhow::ensure!(!path.is_symlink(), "symlink payload {name}");
            }
            anyhow::ensure!(path.is_file(), "not a payload file {name}");
            let hash = digest(&path)?;
            anyhow::ensure!(
                expected.as_str() == Some(hash.as_str()),
                "changed package payload {name}"
            );
            let size = fs::metadata(&path)?.len();
            anyhow::ensure!(
                size > 0 && size <= 64 * 1024 * 1024,
                "payload size unsupported: {name}"
            );
            total_bytes += size;
            anyhow::ensure!(
                total_bytes <= 128 * 1024 * 1024,
                "installer payload exceeds 128 MiB"
            );
            id += 1;
            header += &format!("{{{os},{id},{size},\"{name}\",\"{hash}\"}},\n");
            // RC compilers do not reliably emit dependencies for RCDATA files.
            // Include each verified digest so a payload-only update rebuilds the
            // resource object even when its path and generated IDs are unchanged.
            resources += &format!("// sha256 {hash}\n{id} RCDATA \"{}\"\n", rc_path(&path)?);
            evidence.push(json!({"os":os,"path":name,"size":size,"sha256":hash}));
        }
    }
    anyhow::ensure!(evidence.len() <= 1024, "too many payloads");
    header += "};\n";
    write_if_changed(&input.join("payload.h"), header.as_bytes())?;
    write_if_changed(&input.join("payload.rc"), resources.as_bytes())?;
    Ok(evidence)
}
pub fn build(root: &Path, output: &Path, prefix: &str) -> Result<()> {
    let evidence = prepare(output)?;
    let input = output.join("build/setup-input");
    let binary = output.join("build/setup");
    run(Command::new("cmake")
        .arg("-S")
        .arg(root.join("tools/setup"))
        .arg("-B")
        .arg(&binary)
        .args(["-G", "Ninja"])
        .arg(format!(
            "-DCMAKE_TOOLCHAIN_FILE={}",
            root.join("support/guest/cmake/mingw-i686.cmake").display()
        ))
        .arg(format!("-DDREAMGPU_MINGW_PREFIX={prefix}"))
        .arg(format!("-DCMAKE_RC_COMPILER={prefix}windres"))
        .arg(format!("-DDREAMGPU_SETUP_INPUT={}", input.display())))?;
    run(Command::new("cmake").arg("--build").arg(&binary))?;
    let exe = binary.join("dreamgpu.exe");
    let dump = capture(Command::new(format!("{prefix}objdump")).arg("-p").arg(&exe))?;
    audit_device_id_import(&dump)?;
    let imports: Vec<_> = dump
        .lines()
        .filter_map(|line| {
            line.trim()
                .strip_prefix("DLL Name:")
                .map(|n| n.trim().to_lowercase())
        })
        .collect();
    anyhow::ensure!(
        !imports.is_empty()
            && imports.iter().all(|n| [
                "kernel32.dll",
                "user32.dll",
                "setupapi.dll",
                "cfgmgr32.dll",
                "advapi32.dll"
            ]
            .contains(&n.as_str())),
        "installer has incompatible runtime imports: {imports:?}"
    );
    let bytes = fs::read(&exe)?;
    let pe =
        u32::from_le_bytes(bytes.get(0x3c..0x40).context("truncated PE")?.try_into()?) as usize;
    anyhow::ensure!(
        bytes.get(pe..pe + 6) == Some(&[b'P', b'E', 0, 0, 0x4c, 0x01])
            && bytes.get(pe + 24 + 48..pe + 24 + 52) == Some(&[4, 0, 0, 0]),
        "installer must be i386 PE4"
    );
    let publishing = output.join(".dreamgpu.exe.new");
    fs::copy(&exe, &publishing)?;
    fs::File::open(&publishing)?.sync_all()?;
    fs::rename(publishing, output.join("dreamgpu.exe"))?;
    let mut inputs = serde_json::Map::new();
    crate::native::record_tree(root, &root.join("tools/setup"), &mut inputs)?;
    for name in [
        "support/guest/cmake/setup.cmake",
        "crates/dreamgpu-build/src/installer.rs",
    ] {
        inputs.insert(name.into(), json!(digest(&root.join(name))?));
    }
    write_json(
        &output.join("installer-manifest.json"),
        &json!({
            "schema":1,"exe":"dreamgpu.exe","sha256":digest(&exe)?,
            "imports":imports,"inputs":inputs,"payloads":evidence,
            "activation":"journalled-system-installation","journal_schema":2,
            "stage":{"journal_schema":1,"ownership":"authenticated-private-staging-tree",
                     "recovery":"resume-exact-owned-prefix-or-durable-cancellation"},
            "global":{"journal_schema":3,
                      "commands":["default install","/continue","/upgrade","/rollback","/uninstall","/repair","/recover"],
                      "completion":"verified-driver-and-six-normal-system-API-proofs",
                      "rollback_history":"restored-installed-parent-remains-upgradeable-and-uninstallable; authenticated-history-bound-32",
                      "repair":"exact-recorded-original-public-runtime-or-win98-cache-only; renew-affected-API-proofs",
                      "recovery":"explicit-NT-reverse-driver-only; durable-origin-bound-independent-executor; immutable-G-D-T-preserved"},
            "driver_binding":{"journal_schemas_read":[1,2,3,4],
                "journal_schema_written":{"win98":3,"windows2000-xp":4},"lineage_schema":1,
                "child_identity_schema":1,
                "startup":"GLOBAL sole owner; standalone persistent Run, exact legacy RunOnce retirement",
                "commands":["/driver-install","/driver-resume","/driver-restore"],
                "previous_bindings":["DreamGPU","Microsoft VGA","unbound NT5 PCI device"],
                "generations":"immutable-original-baseline-and-immediate-before-rollback",
                "verification":"started-devnode-and-driver-protocol",
                "resident_build_hash_available":false},
            "runtime_acceptance":"recorded-separately-against-exact-installer-and-fixture-identities"
        }),
    )
}

#[cfg(test)]
mod import_tests {
    use super::audit_device_id_import;

    #[test]
    fn windows98_device_id_uses_its_actual_exporting_module() {
        let correct = "DLL Name: CFGMGR32.dll\n ad310 86 CM_Get_Device_IDA\n\
                       DLL Name: SETUPAPI.dll\n ad340 319 SetupDiDestroyDeviceInfoList\n";
        assert!(audit_device_id_import(correct).is_ok());
        assert!(audit_device_id_import(&correct.replace("CFGMGR32", "SETUPAPI")).is_err());
        assert!(audit_device_id_import("DLL Name: CFGMGR32.dll\n").is_err());
        assert!(audit_device_id_import(&format!("{correct}{correct}")).is_err());
    }
}
fn write_if_changed(path: &Path, bytes: &[u8]) -> Result<()> {
    if fs::read(path).ok().as_deref() != Some(bytes) {
        fs::write(path, bytes)?;
    }
    Ok(())
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn payload_paths_reject_windows_aliases_and_escapes() {
        for name in [
            "../x", "/x", "C:/x", "a//b", "a/", "a./b", "CON.txt", "x/Lpt1", "a\\b", "x\nfile",
        ] {
            assert!(!safe_name(name), "{name}");
        }
        assert!(safe_name("application/dgpugl.dll"));
        assert!(safe_name("licenses/attribution/sources.json"));
    }
    #[test]
    fn package_corruption_is_rejected_before_resource_publication() -> Result<()> {
        let root =
            std::env::temp_dir().join(format!("dreamgpu-setup-manifest-{}", std::process::id()));
        fs::create_dir(&root)?;
        struct Cleanup(std::path::PathBuf);
        impl Drop for Cleanup {
            fn drop(&mut self) {
                let _ = fs::remove_dir_all(&self.0);
            }
        }
        let _cleanup = Cleanup(root.clone());
        for os in ["win98", "windows2000-xp"] {
            let package = root.join("packages").join(os);
            fs::create_dir_all(package.join("application"))?;
            fs::write(package.join("application/test.dll"), b"payload")?;
            for name in ["package.json", "runner_manifest.json"] {
                fs::write(package.join(name), b"{}")?;
            }
            write_json(
                &package.join("manifest.json"),
                &json!({"guest_os":os,"files":{"application/test.dll":digest(&package.join("application/test.dll"))?}}),
            )?;
        }
        let evidence = prepare(&root)?;
        assert_eq!(evidence.len(), 8);
        let header = fs::read(root.join("build/setup-input/payload.h"))?;
        let resource = fs::read(root.join("build/setup-input/payload.rc"))?;
        fs::write(
            root.join("packages/windows2000-xp/application/test.dll"),
            b"changed",
        )?;
        assert!(prepare(&root)
            .unwrap_err()
            .to_string()
            .contains("changed package"));
        assert_eq!(fs::read(root.join("build/setup-input/payload.h"))?, header);
        let package = root.join("packages/windows2000-xp");
        write_json(
            &package.join("manifest.json"),
            &json!({"guest_os":"windows2000-xp","files":{
            "application/test.dll":digest(&package.join("application/test.dll"))?}}),
        )?;
        prepare(&root)?;
        assert_ne!(
            fs::read(root.join("build/setup-input/payload.rc"))?,
            resource,
            "payload-only changes must invalidate the resource compiler input"
        );
        Ok(())
    }
}
